-- Хозяйственный каталог заявок из списка ресторана (RTF). Идемпотентно.
-- Старые household-категории/позиции деактивируем, грузим чистый каталог.
UPDATE requisition_categories SET active=false WHERE kind='household';
UPDATE requisition_catalog_items SET active=false WHERE kind='household';

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Упаковка и одноразовая посуда','household',110,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-001', c.id, 'Соусники пластиковые с крышкой 50 мл', 'household', 0, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-002', c.id, 'Крафтовые супницы с крышкой', 'household', 1, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-003', c.id, 'Крафтовые контейнеры с крышкой', 'household', 2, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-004', c.id, 'Контейнер для бургера', 'household', 3, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-005', c.id, 'Коробки для пиццы 26×26', 'household', 4, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-006', c.id, 'Крафтовые стаканы 400 мл', 'household', 5, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-007', c.id, 'Крышки чёрные к кофейному стакану', 'household', 6, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-008', c.id, 'Стаканы матовые bubble cup tea 500 мл', 'household', 7, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-009', c.id, 'Крышки к bubble cup', 'household', 8, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-010', c.id, 'Контейнеры пластиковые 1 л и крышки к ним', 'household', 9, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-011', c.id, 'Контейнер круглый пластик чёрный 400 мл и крышка', 'household', 10, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-012', c.id, 'Крафтовые пакеты с ручкой', 'household', 11, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-013', c.id, 'Конверт крафтовый для приборов', 'household', 12, true FROM requisition_categories c WHERE c.name='Упаковка и одноразовая посуда' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Одноразовые приборы и аксессуары','household',111,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-014', c.id, 'Пластиковые вилки', 'household', 0, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-015', c.id, 'Пластиковые ножи', 'household', 1, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-016', c.id, 'Пластиковые ложки суповые', 'household', 2, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-017', c.id, 'Палочки для роллов бамбуковые (инд. упаковка)', 'household', 3, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-018', c.id, 'Шпажки с бусиной', 'household', 4, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-019', c.id, 'Трубочки прозрачные', 'household', 5, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-020', c.id, 'Зубочистки (инд. упаковка)', 'household', 6, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-021', c.id, 'Бамбуковая пика «гольф» 12 см', 'household', 7, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-022', c.id, 'Прищепки 2,5 см', 'household', 8, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-023', c.id, 'Бечёвка (шпагат)', 'household', 9, true FROM requisition_categories c WHERE c.name='Одноразовые приборы и аксессуары' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Салфетки, полотенца, гигиена для гостей','household',112,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-024', c.id, 'Салфетки Шампань 33×33', 'household', 0, true FROM requisition_categories c WHERE c.name='Салфетки, полотенца, гигиена для гостей' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-025', c.id, 'Салфетки чёрные 24×24', 'household', 1, true FROM requisition_categories c WHERE c.name='Салфетки, полотенца, гигиена для гостей' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-026', c.id, 'Влажные салфетки (инд. упаковка)', 'household', 2, true FROM requisition_categories c WHERE c.name='Салфетки, полотенца, гигиена для гостей' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-027', c.id, 'Бумажные полотенца (V-сложения)', 'household', 3, true FROM requisition_categories c WHERE c.name='Салфетки, полотенца, гигиена для гостей' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-028', c.id, 'Туалетная бумага гостевая', 'household', 4, true FROM requisition_categories c WHERE c.name='Салфетки, полотенца, гигиена для гостей' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-029', c.id, 'Мыло в гостевую уборную', 'household', 5, true FROM requisition_categories c WHERE c.name='Салфетки, полотенца, гигиена для гостей' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-030', c.id, 'Перчатки чёрные для гостей L', 'household', 6, true FROM requisition_categories c WHERE c.name='Салфетки, полотенца, гигиена для гостей' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Уборочная химия и чистящие средства','household',113,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-031', c.id, 'DESO дезинфицирующее средство', 'household', 0, true FROM requisition_categories c WHERE c.name='Уборочная химия и чистящие средства' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-032', c.id, 'Средство для мытья стекол и зеркал', 'household', 1, true FROM requisition_categories c WHERE c.name='Уборочная химия и чистящие средства' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-033', c.id, 'Азелит (антижир)', 'household', 2, true FROM requisition_categories c WHERE c.name='Уборочная химия и чистящие средства' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-034', c.id, 'Моющее средство для посуды', 'household', 3, true FROM requisition_categories c WHERE c.name='Уборочная химия и чистящие средства' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-035', c.id, 'Гель «Белизна»', 'household', 4, true FROM requisition_categories c WHERE c.name='Уборочная химия и чистящие средства' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-036', c.id, 'Санокс — чистящее для сантехники', 'household', 5, true FROM requisition_categories c WHERE c.name='Уборочная химия и чистящие средства' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-037', c.id, 'Чистин — чистящее с хлором', 'household', 6, true FROM requisition_categories c WHERE c.name='Уборочная химия и чистящие средства' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-038', c.id, 'Сода пищевая', 'household', 7, true FROM requisition_categories c WHERE c.name='Уборочная химия и чистящие средства' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Уборочный инвентарь и ветошь','household',114,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-039', c.id, 'Губки для мытья посуды', 'household', 0, true FROM requisition_categories c WHERE c.name='Уборочный инвентарь и ветошь' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-040', c.id, 'Губки для посуды из нержавейки', 'household', 1, true FROM requisition_categories c WHERE c.name='Уборочный инвентарь и ветошь' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-041', c.id, 'Микрофибра', 'household', 2, true FROM requisition_categories c WHERE c.name='Уборочный инвентарь и ветошь' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-042', c.id, 'Вафельное полотно', 'household', 3, true FROM requisition_categories c WHERE c.name='Уборочный инвентарь и ветошь' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-043', c.id, 'Тряпка для мытья пола', 'household', 4, true FROM requisition_categories c WHERE c.name='Уборочный инвентарь и ветошь' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-044', c.id, 'Протирка голубая (рулон)', 'household', 5, true FROM requisition_categories c WHERE c.name='Уборочный инвентарь и ветошь' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Для персонала и кухни','household',115,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-045', c.id, 'Перчатки кухонные M', 'household', 0, true FROM requisition_categories c WHERE c.name='Для персонала и кухни' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-046', c.id, 'Перчатки кухонные L', 'household', 1, true FROM requisition_categories c WHERE c.name='Для персонала и кухни' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-047', c.id, 'Фартуки полиэтиленовые 80×120', 'household', 2, true FROM requisition_categories c WHERE c.name='Для персонала и кухни' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-048', c.id, 'Мыло для персонала (staff)', 'household', 3, true FROM requisition_categories c WHERE c.name='Для персонала и кухни' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Кухонные расходные материалы','household',116,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-049', c.id, 'Плёнка пищевая (30 и 45 см)', 'household', 0, true FROM requisition_categories c WHERE c.name='Кухонные расходные материалы' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-050', c.id, 'Фольга в рулоне 45 см', 'household', 1, true FROM requisition_categories c WHERE c.name='Кухонные расходные материалы' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-051', c.id, 'Пергамент силиконизированный', 'household', 2, true FROM requisition_categories c WHERE c.name='Кухонные расходные материалы' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-052', c.id, 'Вакуумные пакеты (160×210, 250×350, 300×400)', 'household', 3, true FROM requisition_categories c WHERE c.name='Кухонные расходные материалы' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-053', c.id, 'Фасовочные пакеты 18×27', 'household', 4, true FROM requisition_categories c WHERE c.name='Кухонные расходные материалы' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Мусорные мешки','household',117,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-054', c.id, 'Мусорные мешки 240 л', 'household', 0, true FROM requisition_categories c WHERE c.name='Мусорные мешки' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-055', c.id, 'Мусорные мешки 120 л', 'household', 1, true FROM requisition_categories c WHERE c.name='Мусорные мешки' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-056', c.id, 'Мусорные мешки 30 л', 'household', 2, true FROM requisition_categories c WHERE c.name='Мусорные мешки' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Свечи, декор, атмосфера','household',118,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-057', c.id, 'Благовония (аромапалочки)', 'household', 0, true FROM requisition_categories c WHERE c.name='Свечи, декор, атмосфера' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-058', c.id, 'Воск и фитиль для свечей', 'household', 1, true FROM requisition_categories c WHERE c.name='Свечи, декор, атмосфера' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-059', c.id, 'Свечи «фонтан»', 'household', 2, true FROM requisition_categories c WHERE c.name='Свечи, декор, атмосфера' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-060', c.id, 'Пиро-бумага', 'household', 3, true FROM requisition_categories c WHERE c.name='Свечи, декор, атмосфера' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Канцелярия и офис','household',119,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-061', c.id, 'Бумага А4', 'household', 0, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-062', c.id, 'Скобы для степлера', 'household', 1, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-063', c.id, 'Блокноты (малые/большие)', 'household', 2, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-064', c.id, 'Ручки, карандаши цветные', 'household', 3, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-065', c.id, 'Корректор, ножницы', 'household', 4, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-066', c.id, 'Скотч малярный', 'household', 5, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-067', c.id, 'Скотч обычный', 'household', 6, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-068', c.id, 'Изолента', 'household', 7, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-069', c.id, 'Маркировочная лента', 'household', 8, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-070', c.id, 'Маркер меловой', 'household', 9, true FROM requisition_categories c WHERE c.name='Канцелярия и офис' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

INSERT INTO requisition_categories (name, kind, sort_order, active) VALUES ('Прочее','household',120,true) ON CONFLICT (name, kind) DO UPDATE SET active=true, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-071', c.id, 'Чековая лента для терминалов широкая', 'household', 0, true FROM requisition_categories c WHERE c.name='Прочее' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-072', c.id, 'Чековая лента для терминалов узкая', 'household', 1, true FROM requisition_categories c WHERE c.name='Прочее' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-073', c.id, 'Газ в баллонах', 'household', 2, true FROM requisition_categories c WHERE c.name='Прочее' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;
INSERT INTO requisition_catalog_items (source_id, category_id, name, kind, sort_order, active) SELECT 'hoz-074', c.id, 'Раскраски для детей', 'household', 3, true FROM requisition_categories c WHERE c.name='Прочее' AND c.kind='household' ON CONFLICT (source_id) DO UPDATE SET active=true, name=EXCLUDED.name, category_id=EXCLUDED.category_id, sort_order=EXCLUDED.sort_order;

