#!/usr/bin/env sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
CREATE USER ${ETNA_APP_USER} WITH PASSWORD '${ETNA_APP_PASSWORD}';
CREATE DATABASE ${ETNA_APP_DB} OWNER ${ETNA_APP_USER};

CREATE USER ${NOCODB_META_USER} WITH PASSWORD '${NOCODB_META_PASSWORD}';
CREATE DATABASE ${NOCODB_META_DB} OWNER ${NOCODB_META_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$ETNA_APP_DB" <<-SQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;
SQL

